### PR TITLE
Enable bundler caching in Travis

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by oliverklee** [comment]
The build still fails. @sikachu Any ideas?

**Comment by sikachu** [comment]
Seeing this:

```
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 0 total gem(s) (Gem::LoadError)
```

It seems like we're hitting our own limitation here ... Appraisal does not work with vendored gem yet. (See #13, #30 and #66)

I can't recall if it was Bundler's fault or our own fault, but I'll be happy to look into it.

**Comment by oliverklee** [comment]
Thanks! :heart:

**Comment by sikachu** [comment]
I've been looking into this, and seems like I could get it to work by installing `bundler` in `tmp/gems`. However, `tmp/gems` got wiped every test run, and that would add a huge overhead to the test time.

So, I think I'm not going to support running Appraisal test suite in vendorized environment. However, I'm already working on using Appraisal in vendorized environment.

Thank you so much for your patch.

**Pull request closed without merging**
