### PR TITLE
Support nesting of Bundler block DSL

### PR DESCRIPTION
**Pull request by mshibuya**
This pull request enables nesting of Bundler block DSL(i.e. `group`, `platforms`, `git`, `path`), which gives ability to express fairly complex dependency in Gemfile.

Any suggestions will be greatly appreciated!

### CODE REVIEW

**Comment by mshibuya** [comment]
Do I have to convert all of existing single-quoted `require`s to double-quoted?
There's many of them..

**Comment by sikachu** [comment]
Thats fine. Please ignore Hound's comment on the quoting. I'll take a look at this this Friday.

Thank you for your patch.

**Comment by sikachu** [comment]
I'm tagging this for 1.1.0.

**Comment by mshibuya** [comment]
Thanks, rebased to the master.

**Comment by mshibuya** [comment]
Did further rebasing. :smiley:

**Comment by sikachu** [comment]
@mshibuya Please don't worry about further rebasing. I'll pull down and fixing the conflict very soon.

**Comment by sikachu** [comment]
I've rebased the patch and made some fix to make sure that it works on Ruby 1.8.7 (as I added that a bit earlier) and merged that as 617e583.

I really like how the code looks now. It's so much cleaner.

Thank you so much for your patch!

**Comment by mshibuya** [comment]
How wonderful, thank you for your hard work!

**Pull request closed without merging**
