### PR TITLE
Add ruby 1.9 hash syntax when appropriate

### PR DESCRIPTION
**Pull request by fosberyi**
* Added method in `utils.rb` to output correct syntax
* Changed unit tests to use `stub_const(RUBY_VERSION)`
* Added helper method for acceptance tests to output correct syntax in fixtures b/c we can't
`stub_const` when we're running commands programatically (e.g., `bundle install`, `appraisal generate`)

### CODE REVIEW

**Comment by fosberyi** [comment]
@sikachu I updated the support classes to have Rake 10.5 for ruby 1.8. The tests were failing on my fork, but not on Thoughtbot's. Anyways, all green and rebased now.

**Comment by tute** [comment]
This looks good to me! Can you please squash your commits together, change the message to your nice PR title and description, and rebase against latest master?

**Comment by tute** [comment]
Looks great to me! @sikachu do you think we should merge this?

**Comment by sikachu** [comment]
I think this looks good. I'll polish it up a bit and merge this into the next version.

**Comment by tute** [comment]
Thank you both! 🎉

**Pull request closed without merging**
