### PR TITLE
Properly auto-install the right bundler version

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
And fix failures.

@nickcharlton This is equivalent to #166, but I included a small fix in the test code, so we can use the latest version of bundler.

### CODE REVIEW

**Comment by nickcharlton** [comment]
Interestingly, this `command.rb` fixes another problem I was trying to solve: #146 and I think is valuable on it's own.

I merged my Ruby update PR (#166) to split this from this PR and just rebased yours (hopefully to save you the bother and not just be annoying…).

It'd be a good to see a test here too. Do you think there's something we could do to ensure this is working?

**Comment by deivid-rodriguez** [comment]
I was thinking that since this patch allows appraisals tests to pass against the latest version of bundler, actually testing against the latest version bundler would be enough to cover the fix (or maybe testing against both 1.17 and 2.1?).

If this needs a more specific test, then I'll try to find out some time to think about it.

**Comment by nickcharlton** [comment]
Right yeah, I agree with that. I'm curious that whilst we're not currently testing this, it's different behaviour and whether or not we should or not.

Incidentally, I tried this branch on [Ruby 2.7 on Administrate](https://github.com/thoughtbot/administrate/pull/1548) and we get some fun errors there: https://circleci.com/gh/thoughtbot/administrate/5904 any thoughts?

**Comment by deivid-rodriguez** [comment]
I'm having a look now :+1:

**Comment by deivid-rodriguez** [comment]
Ok, so this PR does fix the issue of auto installing the correct `bundler` version your CI wants to use (in the case of administrate, 1,17.3).

However, that reveals a potential incompatibility between bundler 1.17 and ruby 2.7 as the errors you reference show.

[Upgrading bundler](https://github.com/thoughtbot/administrate/compare/nc-test-against-ruby-27...deivid-rodriguez:nc-test-against-ruby-27) gets past that issue, but [reveals yet another incompatibility, in this case between ruby 2.7 and rails 4.2](https://app.circleci.com/jobs/github/deivid-rodriguez/administrate/11/parallel-runs/0/steps/0-111).

You might be able to fix that last issue by pinning administrate the `bigdecimal 1.x`, but honestly I think the best way to "fix" it is by dropping Rails 4.2 support.

**Comment by deivid-rodriguez** [comment]
Any news @nickcharlton? :)

**Comment by nickcharlton** [comment]
I think on further thought that this is the right approach to take, so I'm going to merge it and see what goes wrong!

**Comment by deivid-rodriguez** [comment]
Thanks @nickcharlton!

**Comment by odlp** [comment]
@nickcharlton 👋 hello! Any chance of cutting a release with this?

**Comment by nickcharlton** [comment]
👋 hello friend!

Yeah — I hadn't revisited since so I must've forgotten about it. I'll do this on Friday (2020-06-05).

**Pull request merged**
